#ifndef SC_MULTICARD_JOYSTICK_H
#define SC_MULTICARD_JOYSTICK_H

#define JOYSTICK_LEFT   2
#define JOYSTICK_RIGHT  1
#define JOYSTICK_UP     8
#define JOYSTICK_DOWN   4
#define JOYSTICK_FIRE   16

#endif //SC_MULTICARD_JOYSTICK_H
